services:
  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/tmp/nginx.conf
    environment:
      - FLASK_SERVER_ADDR=backend:9091
    command: >
      /bin/sh -c "envsubst '\$${FLASK_SERVER_ADDR}' < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    depends_on:
      - backend

  backend:
    build:
      context: flask
      target: builder
    stop_signal: SIGINT
    environment:
      - FLASK_SERVER_PORT=9091
    env_file:
      - .env
    volumes:
      - /opt/whisper-models/tiny:/models
      - ./flask:/src
    ports:
      - "9091:9091"



